### ISSUE TITLE
Need codereview !

### ISSUE THREAD

**Issue by felixSabatie** [PolytechLyon/isi3-tp1-graph-sabatie#1]
Je pense avoir fini la partie code de mon projet, la dernière version de ce que j'ai fait est sur la branche develop

**Comment by Slashgear** [comment]
Peux-tu merger et faire ton rapport avant de demander la review 😉

**Comment by felixSabatie** [comment]
Je fais ça tout de suite

**Comment by felixSabatie** [comment]
C'est fait

**Comment by Slashgear** [comment]
- [ ] 💡 dans cette réponse je verrais bien un petit UML pour être sur que tu as bien compris https://github.com/PolytechLyon/isi3-tp1-graph-sabatie/blob/master/RAPPORT.md#question-2

- [ ]  Dans ce cas, est-ce que créer des variables apporte vraiment quelque chose ? 
https://github.com/PolytechLyon/isi3-tp1-graph-sabatie/blob/07b3d710f8f4621223cfc2d9558200bd7d8aa075/src/main/java/graph/UndirectedGraph.java#L16-L21

- [ ] Peut-tu m'expliquer en quoi utiliser le pattern Iterator apport un avantage ? 

- [ ] Ici le type Graph peut-être remplacé par IGraph, pourquoi ?

https://github.com/PolytechLyon/isi3-tp1-graph-sabatie/blob/07b3d710f8f4621223cfc2d9558200bd7d8aa075/src/main/java/graph/UndirectedGraph.java#L9

- [x] La class abstraite pour les deux iterator c'est 🔝 

- [ ] La class Node ne surcharge pas la méthode hashcode, peux-tu m'expliquer ce que cela peut avoir comme conséquence ?

**Comment by felixSabatie** [comment]
Merci du retour, je m'occupe de tout ça quand j'ai le temps

**Comment by Slashgear** [comment]
Aller c'est pas mal !
